### ISSUE TITLE
negative days

### ISSUE THREAD

**Issue by artulloss** [SonsaYT04/TempBanUI#10]
Player's don't get unbanned when the time is up from what I can tell

**Comment by SonsaYT04** [comment]
Please provide screenshots. Did you check it with /tcheck

**Comment by artulloss** [comment]
![](https://i.imgur.com/sKJIqrg.jpg)

**Comment by SonsaYT04** [comment]
Please provide a console error, and explain it briefly where it starts happen, what version etc.

**Comment by artulloss** [comment]
I don't believe I've ever seen any errors with the plugin, I'm running alpha 12 stable if that helps

**Comment by artulloss** [comment]
Wow helpful

**Comment by phcserver** [comment]
It will automatically delete if they joined the server.

**Comment by SonsaYT04** [comment]
It will automatically delete if the ban player join your server.

**Comment by SonsaYT04** [comment]
Fixed on 1.5 update
