### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by treehousemc1** [SonsaYT04/TempBanUI#14]
Server thread/CRITICAL Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'FormAPI v1.2.0': Argument 2 passed to SonsaYT\TempBanUI\Main::SonsaYT\TempBanUI\{closure}() must be of the type array or null, integer given, called in /plugins/FormAPI-master/src/jojoe77777/FormAPI/FormAPI.php on line 75 on jojoe77777\FormAPI\FormAPI
07.07 07:47:36 [Server] Server thread/CRITICAL TypeError: "Argument 2 passed to SonsaYT\TempBanUI\Main::SonsaYT\TempBanUI\{closure}() must be of the type array or null, integer given, called in /plugins/FormAPI-master/src/jojoe77777/FormAPI/FormAPI.php on line 75" (EXCEPTION) in "TempBanUI/src/SonsaYT/TempBanUI/Main" at line 117

**Comment by SonsaYT04** [comment]
Follow this step, and if you still encounter this error just let me know.
- Please use it on a clean server.
- Delete your old TempBan folder.
- Use pmmp latest released version

**Comment by treehousemc1** [comment]
@SonsaYT04 Theres no errors in console log now but /tcheck not working

**Comment by SonsaYT04** [comment]
I tested it on new pmmp version. No errors. Please make sure to use the latest pmmp and FormAPI version.
