### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by treehousemc1** [SonsaYT04/TempBanUI#17]
Server thread/CRITICAL Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'FormAPI v1.2.0': Object of class SQLite3Result could not be converted to int on jojoe77777\FormAPI\FormAPI
24.07 16:41:00 [Server] Server thread/CRITICAL ErrorException: "Object of class SQLite3Result could not be converted to int" (EXCEPTION) in "TempBanUI/src/SonsaYT/TempBanUI/Main" at line 72

**Comment by SonsaYT04** [comment]
[Check This](https://github.com/SonsaYT04/TempBanUI/issues/16)
