### ISSUE TITLE
TempBanUI ban another player than player chosen on the list

### ISSUE THREAD

**Issue by Antoine2lop** [SonsaYT04/TempBanUI#19]
i have a problem with TempBanUI when server have a lot of players connected (40-60 on my server)
i open players list and select a player to ban (player A for example)
but player list don't refresh when anothers players connect or disconnect
when i click to submit button  to ban player A (panel show choose player : player A) but TempBanUI ban another player (player B for example)
it's a problem of refresh / selection list 

sorry for my bad english

TempBanUI_dev-54
https://poggit.pmmp.io/r/36925/TempBanUI_dev-54.phar

FormAPI_dev-5
https://poggit.pmmp.io/r/34221/FormAPI_dev-5.phar

PocketMine-MP/1386/
https://jenkins.pmmp.io/job/PocketMine-MP/1386/

**Comment by SonsaYT04** [comment]
If /tban was executed, all player will be put in array. Even though player leave, they can still be ban and may not cause to ban random player.

List won't refresh until you execute /tban again.
