### ISSUE TITLE
add unban command

### ISSUE THREAD

**Issue by teracube** [SonsaYT04/TempBanUI#2]
i suggest add unban command 
thanks

**Comment by SonsaYT04** [comment]
Thanks for your suggestion. I'll update this plugin tom.

**Comment by SonsaYT04** [comment]
Hi @teracube . I already added unban feature.
To see all changelog you can visit [WIKI](https://github.com/SonsaYT04/TempBanUI/wiki).

NOTE: Please delete the old TempBan folder and plugin to load new message config and database.

**Comment by teracube** [comment]
thanks
