### ISSUE TITLE
help

### ISSUE THREAD

**Issue by cujowilliams123** [SonsaYT04/TempBanUI#20]
when i do /tban and click on someone's name and put a amount of time and reason and then i click Submit nothing happens idk why

**Comment by SonsaYT04** [comment]
Do you use latest TempBan and FormAPI?
What is your server version?

**Comment by cujowilliams123** [comment]
3.2.1

**Comment by SonsaYT04** [comment]
Hello, TempBan is working to pmmp 3.2.3 version and up. Please download the latest TempBanUI & FormAPI.

Check this screenshot.
https://ibb.co/imVLYp
