### ISSUE TITLE
synchronise sql

### ISSUE THREAD

**Issue by LeoBdt** [SonsaYT04/TempBanUI#28]
hello is it planned to add a option to have a online db ?

**Comment by SonsaYT04** [comment]
You mean mysql? Nope

**Comment by LeoBdt** [comment]
Yes because it use a local database and it'd be very helful because i've many servers.... is it too hard ????

**Comment by SonsaYT04** [comment]
It's not hard, but most of network servers have their own developer so they don't use public plugin like this. So it's useless if I support mysql.
