### ISSUE TITLE
What about a Message why the person is banned?

### ISSUE THREAD

**Issue by UnexMC** [SonsaYT04/TempBanUI#3]

**Comment by SonsaYT04** [comment]
Thanks for your suggestion. I'll update this plugin tom.

**Comment by UnexMC** [comment]
cool!
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 20.03.18, 15:15, SonsaYT <notifications@github.com> schrieb:
Thanks for your suggestion. I'll update this plugin tom.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SonsaYT04/TempBanUI","title":"SonsaYT04/TempBanUI","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SonsaYT04/TempBanUI"}},"updates":{"snippets":[{"icon":"PERSON","message":"@SonsaYT04 in #3: Thanks for your suggestion. I'll update this plugin tom."}],"action":{"name":"View Issue","url":"https://github.com/SonsaYT04/TempBanUI/issues/3#issuecomment-374613061"}}}

**Comment by UnexMC** [comment]
cool!

**Comment by SonsaYT04** [comment]
Hi @UnexMC . I already added ban reason feature.
To see all changelog you can visit [WIKI](https://github.com/SonsaYT04/TempBanUI/wiki).

NOTE: Please delete the old TempBan folder and plugin to load new message config and database.

**Comment by UnexMC** [comment]
Whats your Email?

**Comment by SonsaYT04** [comment]
Why?
