### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by onykcz** [SonsaYT04/TempBanUI#32]
hello I need help every time dam / tban throws me out of the server and writes "Internal Server Error" everything I need to help. :(

**Comment by dadodasyra** [comment]
send complete error

**Comment by onykcz** [comment]
> send complete error
 
16:10:45] [Server thread/ERROR]: Could not load plugin 'FormAPI': Incompatible API version (plugin requires one of: 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12)

[16:21:48] [Server thread/CRITICAL]: Error: "Call to a member function createSimpleForm() on null" (EXCEPTION) in "plugins/TempBanUI_dev-83 (2).phar/src/SonsaYT/TempBanUI/Main" at line 89

**Comment by Sonsa04** [comment]
Update your FormAPI plugin

**Comment by onykcz** [comment]
> Update your FormAPI plugin

Link Pls :))
