### ISSUE TITLE
How do you unban someone?

### ISSUE THREAD

**Issue by minijaham** [SonsaYT04/TempBanUI#35]
I have tried several stuff like using the default pmmp’s /unban and /pardon, but both /tban nor /tcheck provided me with instruction of how to unban a player who is banned. I have struggled this with few of my staff members on my server, and eventually had to delete the plugin to unban the banned. Please tell me how to unban!

**Comment by Endermanbugzjfc** [comment]
> I have tried several stuff like using the default pmmp’s /unban and /pardon, but both /tban nor /tcheck provided me with instruction of how to unban a player who is banned. I have struggled this with few of my staff members on my server, and eventually had to delete the plugin to unban the banned. Please tell me how to unban!

u can unban someone with the /tban UI lmao, just click on the names. Or u can decrypt the sqlite db file and directly yeet the player out of the table

**Comment by minijaham** [comment]
There is literally no fucking way to unban. I don't see any ppl listed in the fucking UI when I ban someone and open the sht up

**Comment by Endermanbugzjfc** [comment]
> There is literally no fucking way to unban. I don't see any ppl listed in the fucking UI when I ban someone and open the sht up

interesting 🤔

so just directly break into the db file and yeet them out of the table :) best way

**Comment by minijaham** [comment]
Alright...Thanks!
