### ISSUE TITLE
Minutes set to 1?

### ISSUE THREAD

**Issue by TheShinPin** [SonsaYT04/TempBanUI#4]
From what I see in the pictures, minutes is auto set to 1. Also a few suggestions :3 a temp mute would be nice, aswell as IP ban and mute. (Not sure if you have the IP ban already) An option in the menu would be cool.

**Comment by TheShinPin** [comment]
Also maybe have the interval of minutes go up by 5

**Comment by SonsaYT04** [comment]
1. Minimum temp ban is 1 min.
2. This is TempBan plugin not complete punishment plugin.
3. Right now we use xbox account, banning name is enough.
