### ISSUE TITLE
Bans a random person if the person being banned disconnects

### ISSUE THREAD

**Issue by artulloss** [SonsaYT04/TempBanUI#7]
Please fix this it causes a lot of falsebans

**Comment by SonsaYT04** [comment]
Please provide a briefly explanations.

**Comment by artulloss** [comment]
when doing /tban and selecting a player to ban, the player can leave while this happens and it will default to a random player

**Comment by SonsaYT04** [comment]
I tested it and it works fine.

If /tban was executed, all player will be put in array. Even though player leave, they can still be ban. And may not cause to ban random player.
