### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MSG100TC** [SonsaYT04/TempBanUI#9]
Ex. {player} is player123
{Staff} is staff123

Originally, When staff123 uses /tban ban a player for 10 days for hacking. Below is the server broadcasts and player123's ban screen.

player123 has been banned for 10 days. Reason: Hacking

You have been banned for 10 days. Reason: Hacking

My idea is that you can add $sender->getName() for all the actions, what I mean by that is instead of only showing, who, why and time you are banned, you show the staff's name too. So it will probably be like:

player123 has been banned by staff123 for 10 days. Reason: Hacking

You have been banned by staff123 for 10 days. Reason: Hacking

The reason I suggest this is that players can appeal against the staff member if its a false ban, and it make it more convenient for server admins to check the logs.

Thanks! Please consider adding that

**Comment by SonsaYT04** [comment]
@MSG100TC Thanks for suggestion, I'll try to add this feature but I don't support 1.2.3 and up right now.

**Comment by MSG100TC** [comment]
Are you going to add it in this update?

**Comment by SonsaYT04** [comment]
Yeah if I have free time, but if you can do that just make a pull request

**Comment by SonsaYT04** [comment]
Still thinking if it's needed

**Comment by SonsaYT04** [comment]
Done. Please check my new release.
